### ISSUE TITLE
making patch file

### ISSUE THREAD

**Issue by madmax765** [blueboy/portal#77]
as i try to make a patch files with latest bot and cmangs pull, I get ton of errors 
http://prntscr.com/8v7dcm
figure then should been none or only a few after 

Merge git://github.com/cmangos/mangos-wotlk
cala committed 5 days ago

 like your portal dose work, I just can't make a patch now

**Comment by cala** [comment]
Your error log suggests that git can't apply the patch to the target repository. Usually, this happens when the source repository (from which the patch was made) and the target repository are different or have merging conflicts. This can also depends on your local settings.

Whatever, this is not an issue related to portal, so I'm closing it. I suggest you have a look at the git documentation for more info regarding the patching process. :smile:

**Comment by madmax765** [comment]
Odd I am making my patch files as i allays made it. And allays the patch as allays the same way as BlueBoy tough me to do.I know its merge conflicts. Uselea a few white spaces  errors. witch i can fix.. for a few lines in the are different... but never this many

i use this to make code
#!/bin/bash -x
git clone git://github.com/cmangos/mangos-wotlk.git portal
cd portal
git fetch git://github.com/blueboy/portal master:portal
git checkout portal
HASH=`git log --pretty=oneline | grep -m 1 '\[1[0-9]\{4\}]' | cut -d " " -f 1`
git diff $HASH > playerbot.patch


and then i use this to apply patch file
git apply --check --whitespace=fix playerbot.patch 

to check before i apply patch file
git apply --whitespace=fix playerbot.patch 

I have done it this was for years.. but scents MaNGOS changes the SD2 into data base  i have not been able to use bot
So why was the way i was tought. dose not work know.. Please any info would be nice
